### ISSUE TITLE
Data - what are we doing with it?

### ISSUE THREAD

**Issue by nvogtvincent** [nvogtvincent/cmip6_arctic_terns#1]
Just noticed @daw538 mentioning netcdf files in the repository structure. Were you intending to actually include them with the manuscript and, if so, where were you planning on archiving them? I've been wondering what to do with my trajectory files since all of my scripts use them as input, but they're 30GB in total (compressed)...

**Edit**: OK, I see they're very small netcdfs. Any thoughts on my 30GB dataset? Is it worth trying to archive them somewhere or nah?

**Comment by daw538** [comment]
Yeah tbh I have no idea what the general practice is when it comes to uploading data for the reproduction of results. I only included those files for now as they're pretty small and are shared between mine and Ned's analysis. To be accurate the data isn't raw CMIP6 data anyway, but has been post-processed to give the multi-model average that is used by all the wind analysis,

**Comment by daw538** [comment]
@nvogtvincent are those trajectory files created by TernSim.py? If so I personally don't see the need for you to include the trajectory files since you've provided the means to recreate them if someone so desires (even if there is a computational cost associated with that).

**Comment by nvogtvincent** [comment]
@daw538 Yeah they are, and yes they are reproducible with TernSim.py. The 'plus' of including the trajectories explicitly is that someone could immediately reproduce all figures in the paper from this repo without spending a lot of (computation) time recomputing trajectories, but archiving it will be a pain and, as you point out, probably unnecessary since the experiments are fairly simple and, realistically, it's unlikely anybody would ever use them. Let's not then.
